

cc_library(
    name = "context",
    srcs = [
        "context.cc",
        "util.cc",
    ],
    hdrs = [
        "context.h",
        "util.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@envoy_wasm_api//:proxy_wasm_intrinsics",
    ],
)


# cc_proto_library(
#     name = "node_info_cc_proto",
#     visibility = ["//visibility:public"],
#     deps = ["node_info_proto"],
# )

# proto_library(
#     name = "node_info_proto",
#     srcs = ["node_info.proto"],
# )
